require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'app/views/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'spec/rswag/**/*'

#
# Layout department
#
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/LineContinuationLeadingSpace:
  Enabled: true
Layout/LineContinuationSpacing:
  Enabled: true
Layout/LineEndStringConcatenationIndentation:
  Enabled: true
Layout/LineLength:
  Max: 120
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
#
# Lint department
#
Lint/EmptyBlock:
  Enabled: true
Lint/DuplicateBranch:
  Enabled: true
Lint/RedundantDirGlobSort:
  Enabled: true
Lint/SymbolConversion:
  Enabled: true
Lint/MissingSuper:
  Enabled: false
#
# Metrics department
#
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
#
# Naming department
#
Naming/BlockForwarding:
  Enabled: true
Naming/PredicateName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
#
# Performance department
#
Performance/MapCompact:
  Enabled: false # disabled as it is unsafe
Performance/StringIdentifierArgument:
  Enabled: true
Performance/StringInclude:
  Enabled: true
#
# Rails department
#
Rails/InverseOf:
  Enabled: false
#
# RSpec department
#
RSpec/AnyInstance:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/LetSetup:
  Enabled: false
RSpec/IndexedLet:
  Enabled: false
RSpec/NestedGroups:
  Max: 6
RSpec/SubjectDeclaration:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false
#
# Style department
#
Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false
