data = [{"id"=>1, "codigo"=>"CM", "nome"=>"CRM - Cons. Reg. de Medicina"}, {"id"=>3, "codigo"=>"CP", "nome"=>"CRP - Cons. Reg. de Psicologia"}, {"id"=>4, "codigo"=>"CN", "nome"=>"COREN - Cons. Reg. de Enfermagem"}, {"id"=>5, "codigo"=>"CC", "nome"=>"CRC - Cons. Reg. de Contabilidade"}, {"id"=>7, "codigo"=>"SP", "nome"=>"SSP - Secretaria de Segurança Publica"}, {"id"=>8, "codigo"=>"MA", "nome"=>"MAE - Comando da Aeronáutica ex. Min. da Aeronáutica"}, {"id"=>9, "codigo"=>"ME", "nome"=>"MEX - Comando do Exército ex. Min. Exército"}, {"id"=>10, "codigo"=>"MM", "nome"=>"MMA - Comando da Marinha ex. Min. Marinha"}, {"id"=>11, "codigo"=>"DP", "nome"=>"DPF - Polícia Federal"}, {"id"=>12, "codigo"=>"IC", "nome"=>"ICLA - Carteira de Identidade Classista"}, {"id"=>13, "codigo"=>"CA", "nome"=>"CRA - Cons. Reg. de Administração"}, {"id"=>14, "codigo"=>"CB", "nome"=>"CRB - Cons. Reg. de Biblioteconomia"}, {"id"=>16, "codigo"=>"CI", "nome"=>"CRECI - Cons. Reg. de Corretores de Imóveis"}, {"id"=>19, "codigo"=>"CE", "nome"=>"CRE - Cons. Reg. de Estatística"}, {"id"=>20, "codigo"=>"CF", "nome"=>"CRF - Cons. Reg. de Farmácia"}, {"id"=>21, "codigo"=>"CT", "nome"=>"CREFITO - Cons. Reg. de Fisioterapia e Terap. Ocup."}, {"id"=>23, "codigo"=>"CV", "nome"=>"CRV - Cons. Reg. de Medicina Veterinária"}, {"id"=>24, "codigo"=>"OB", "nome"=>"OMB - Ordens dos Músicos do Brasil"}, {"id"=>25, "codigo"=>"CN", "nome"=>"CRN - Cons. Reg. de Nutrição"}, {"id"=>26, "codigo"=>"CO", "nome"=>"CRO - Cons. Reg. de Odontologia"}, {"id"=>27, "codigo"=>"RP", "nome"=>"CRPRE - Cons. Reg. de Profis. Relac. Públicas"}, {"id"=>29, "codigo"=>"CQ", "nome"=>"CRQ - Cons. Reg. de Química"}, {"id"=>30, "codigo"=>"RC", "nome"=>"CRRC - Cons. Reg. de Repres. Comerciais"}, {"id"=>31, "codigo"=>"OA", "nome"=>"OAB - Ordem dos Advogados do Brasil"}, {"id"=>32, "codigo"=>"OU", "nome"=>"OUT - Outros Emissores"}, {"id"=>33, "codigo"=>"ES", "nome"=>"EST - Documentos Estrangeiros"}, {"id"=>34, "codigo"=>"OM", "nome"=>"OM - Organismos Militares"}, {"id"=>35, "codigo"=>"BI", "nome"=>"CRBIO - Conselho Regional de Biologia"}, {"id"=>36, "codigo"=>"BM", "nome"=>"CRBM - Conselho Regional de Biomedicina"}, {"id"=>37, "codigo"=>"OP", "nome"=>"CROP - Conselho Regional de Ópticos"}, {"id"=>38, "codigo"=>"TR", "nome"=>"CRTR - Conselho Reg. de Téc. de Radiologia"}, {"id"=>39, "codigo"=>"EC", "nome"=>"CREC - Conselho Regional de Economia"}, {"id"=>40, "codigo"=>"FS", "nome"=>"CRFIS - Conselho Regional de Física"}, {"id"=>41, "codigo"=>"FO", "nome"=>"CRFO - Conselho Regional de Fonoaudiologia"}, {"id"=>42, "codigo"=>"PE", "nome"=>"CRPED - Conselho Regional de Pedagogia"}, {"id"=>43, "codigo"=>"RR", "nome"=>"CRRAD - Conselho Regional de Radiologia"}, {"id"=>44, "codigo"=>"SS", "nome"=>"CRESS - Cons. Reg. de Serviço Social"}, {"id"=>45, "codigo"=>"MV", "nome"=>"CRMV - Cons. Reg. de Medicina Veterinária"}, {"id"=>2, "codigo"=>"CE", "nome"=>"CREA - Cons. Reg. de Eng. e Agronomia"}]

data.each do |conselho_classe|
  next if ConselhoClasse.exists?(nome: conselho_classe['nome'])

  ConselhoClasse.create(conselho_classe)

  puts "ConselhoClasse #{conselho_classe['nome']} criado com sucesso"
end
