data = [{"id"=>27, "nome"=>"Tocantins", "uf"=>"TO", "pais_id"=>24, "codigo_dne"=>"24"},
        {"id"=>26, "nome"=>"Sergipe", "uf"=>"SE", "pais_id"=>24, "codigo_dne"=>"27"},
        {"id"=>25, "nome"=>"São Paulo", "uf"=>"SP", "pais_id"=>24, "codigo_dne"=>"26"},
        {"id"=>24,
         "nome"=>"Santa Catarina",
         "uf"=>"SC",
         "pais_id"=>24,
         "codigo_dne"=>"25"},
        {"id"=>23, "nome"=>"Roraima", "uf"=>"RR", "pais_id"=>24, "codigo_dne"=>"09"},
        {"id"=>22, "nome"=>"Rondônia", "uf"=>"RO", "pais_id"=>24, "codigo_dne"=>"23"},
        {"id"=>21,
         "nome"=>"Rio Grande do Sul",
         "uf"=>"RS",
         "pais_id"=>24,
         "codigo_dne"=>"22"},
        {"id"=>20,
         "nome"=>"Rio Grande do Norte",
         "uf"=>"RN",
         "pais_id"=>24,
         "codigo_dne"=>"21"},
        {"id"=>19,
         "nome"=>"Rio de Janeiro",
         "uf"=>"RJ",
         "pais_id"=>24,
         "codigo_dne"=>"20"},
        {"id"=>18, "nome"=>"Piauí", "uf"=>"PI", "pais_id"=>24, "codigo_dne"=>"19"},
        {"id"=>17,
         "nome"=>"Pernambuco",
         "uf"=>"PE",
         "pais_id"=>24,
         "codigo_dne"=>"18"},
        {"id"=>16, "nome"=>"Paraná", "uf"=>"PR", "pais_id"=>24, "codigo_dne"=>"17"},
        {"id"=>15, "nome"=>"Paraíba", "uf"=>"PB", "pais_id"=>24, "codigo_dne"=>"16"},
        {"id"=>14, "nome"=>"Pará", "uf"=>"PA", "pais_id"=>24, "codigo_dne"=>"15"},
        {"id"=>13,
         "nome"=>"Minas Gerais",
         "uf"=>"MG",
         "pais_id"=>24,
         "codigo_dne"=>"14"},
        {"id"=>12,
         "nome"=>"Mato Grosso do Sul",
         "uf"=>"MS",
         "pais_id"=>24,
         "codigo_dne"=>"13"},
        {"id"=>11,
         "nome"=>"Mato Grosso",
         "uf"=>"MT",
         "pais_id"=>24,
         "codigo_dne"=>"12"},
        {"id"=>10, "nome"=>"Maranhão", "uf"=>"MA", "pais_id"=>24, "codigo_dne"=>"11"},
        {"id"=>9, "nome"=>"Goiás", "uf"=>"GO", "pais_id"=>24, "codigo_dne"=>"10"},
        {"id"=>8,
         "nome"=>"Espírito Santo",
         "uf"=>"ES",
         "pais_id"=>24,
         "codigo_dne"=>"08"},
        {"id"=>7,
         "nome"=>"Distrito Federal",
         "uf"=>"DF",
         "pais_id"=>24,
         "codigo_dne"=>"07"},
        {"id"=>6, "nome"=>"Ceará", "uf"=>"CE", "pais_id"=>24, "codigo_dne"=>"06"},
        {"id"=>5, "nome"=>"Bahia", "uf"=>"BA", "pais_id"=>24, "codigo_dne"=>"05"},
        {"id"=>4, "nome"=>"Amazonas", "uf"=>"AM", "pais_id"=>24, "codigo_dne"=>"04"},
        {"id"=>3, "nome"=>"Amapá", "uf"=>"AP", "pais_id"=>24, "codigo_dne"=>"03"},
        {"id"=>2, "nome"=>"Alagoas", "uf"=>"AL", "pais_id"=>24, "codigo_dne"=>"02"},
        {"id"=>1, "nome"=>"Acre", "uf"=>"AC", "pais_id"=>24, "codigo_dne"=>"01"}]

data.each do |estado|
  next if Estado.exists?(nome: estado['nome'])

  Estado.create(estado)

  puts "Estado #{estado['nome']} criado com sucesso"
end
