name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  pipeline:
    uses: OM30/pipelines/.github/workflows/ci.yaml@v1.0.7
    with:
      os_version: "ubuntu-latest"
    secrets:
      BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${{ secrets.BUNDLE_RUBYGEMS__PKG__GITHUB__COM }}
